project_id = "cqwuklripymvwhqbvzlc"

[functions.parse-script]
verify_jwt = false

[functions.analyze-content-safety]
verify_jwt = false

[functions.compile-generation-payload]
verify_jwt = false

[functions.generate-headshot]
verify_jwt = false

[functions.analyze-reference-image]
verify_jwt = false

[functions.generate-asset-options]
verify_jwt = false
